framework:
    secret: '%env(APP_SECRET)%'
    default_locale: 'en'
    #csrf_protection: true
    #http_method_override: true
    translator:
        fallbacks: ['en']

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        enabled: true
        cookie_secure: auto
        cookie_samesite: lax
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        cookie_lifetime: 2592000000
        gc_maxlifetime: 2592000000

    #esi: true
    #fragments: true
    php_errors:
        log: true
