lexik_jwt_authentication:
    private_key_path: '%env(resolve:JWT_SECRET_KEY)%'
    public_key_path: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 2600000 # change token_ttl later (original: 3600)